# -*- coding: utf-8 -*-
"""AEOPDay7Pil.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1or1No_BBPajZkMk2SQq-ZWZXSw7NcZS2

# ARGUMENTS
"""

from PIL import Image
import argparse
def a():
    print("a")
def b():
    print("b")
def main():
    a()
    b()
if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--num', type=int, required=True, help="choose between a=1 and b=2")
    args = parser.parse_args()
    if args.num == 1:
        a()
    elif args.num == 2:
        b()
    else:
        main()

"""# PIL EXERCISES"""



"""1. Open Image"""

import PIL
from PIL import Image
import matplotlib.pyplot as plt
import numpy as np
import os

image1  = Image.open('playground1.JPG')

plt.imshow(image1)
image1.show()

"""2) Intro, New"""

from PIL import Image 
size = width, height = 320, 240
image = Image.new("RGB", size, "white")
plt.imshow(image)
## makes a square with color, not sure where to view besides having to save it as a file

"""3. Blend"""

from PIL import Image
import matplotlib.pyplot as plt
import os
import numpy as np

def main( ):
  filename_one = "playground1.JPG";
  filename_two = "playground2.JPG";

  image_one = Image.open( filename_one );
  image_two = Image.open( filename_two );

  image_blended = Image.blend(image_one, image_two, 0.5);
  image_blended.show()
  del image_one, image_two;

  plt.imshow(image_blended)

#image_blended.save()
if (__name__ == "__main__"): 
   main();

"""4. Composite"""

from PIL import Image

"""filename_one = "playground1.JPG"
filename_two = "playground2.JPG"

image_one = Image.open( filename_one );
image_two = Image.open( filename_two );
  
image_composite = Image.composite( image_one, image_two, image_one);
image_composite.show()"""

mask = Image.new("L", image_one.size, 0)
image_comp = Image.composite( image_one, image_two, mask)
plt.imshow(image_comp)

 #bad transparency mask?

"""5. Convert(Grayscale)"""

from PIL import Image

def main( ):
  filename = "playground1.JPG"
  image = Image.open( filename );

  image_gray = image.convert("L" ); #L turns an rbg fiile to grayscale
  plt.imshow(image_gray, cmap = 'gray');
  del image;

if(__name__ == "__main__"):
  main();

"""6. Crop"""

from PIL import Image

filename = "playground1.JPG"
image = Image.open( filename );

image_crop = image.crop((200, 200, 800, 800))#pick dimension sizes, centered where and how much

plt.imshow(image_crop)

"""7. Filter"""

from PIL import Image
from PIL import ImageFilter

image1 = image.filter(ImageFilter.GaussianBlur(radius=1))
plt.imshow(image1)

#image.filter( ImageFilter.CONTOUR ).show(); 
image.filter( ImageFilter.DETAIL ).show();
#Edge_Enhance another option, Emboss, Find_Edges (returns outline)

"""8. Find Size"""

#how do we find the size of the image
from PIL import Image
from PIL import ImageFilter

filename = "playground1.JPG"
image = Image.open( filename );

print(image.size) #finds image size
#size = width, height, image.size;

"""9. Get Colors"""

from PIL import Image
from PIL import ImageFilter

filename = "playground1.JPG"
image = Image.open( filename );
size = width, height, = image.size;
colors = image.getcolors(width*height); #doesn't return colors it sees when left empty
print(colors)                           #now it returned the colors it found and count of how many times 
                                          #it identified that color

"""10. Get Pixel"""

#retrieve a pixel
from PIL import Image
from PIL import ImageFilter

filename = "playground1.JPG"
image = Image.open( filename );
size = width, height, = image.size;

coordinate = x, y = 180, 60
print(image.getpixel( coordinate )); #returns color and data image at that point in RGBA

"""11. Get Data"""

from PIL import Image
from PIL import ImageFilter

filename = "playground1.JPG"
image = Image.open( filename );
size = width, height, = image.size;

print( list(image.getdata())); #didn't run because said it would crash

"""12. Paste (overlay)"""

#paste function to overlay images
from PIL import Image
from PIL import ImageFilter

filename = "playground1.JPG"
image = Image.open( filename )
size = width, height, = image.size

image_overlay = image.paste("blue", (80, 20, 180, 200))
plt.imshow(image_overlay)

"""13. Thumbnail"""

from PIL import Image
from PIL import ImageFilter

filename = "playground1.JPG"
image = Image.open( filename )
size = width, height, = image.size

image1 = image.thumbnail((300, 300))
plt.imshow(image1)

"""14. Resize"""

#resize an image
from PIL import Image
from PIL import ImageFilter

filename = "playground1.JPG"
image = Image.open( filename )
size = width, height, = image.size

image1 = image.resize((500, 100))

plt.imshow(image1)

"""15. Rotate"""

#rotate an image
from PIL import Image
from PIL import ImageFilter

filename = "playground1.JPG"
image = Image.open( filename )
size = width, height, = image.size

image1 = image.rotate( 90 )
plt.imshow(image1)